[package]
name = "capstone-sys"
version = "0.3.0"
authors = ["m4b <m4b.github.io@gmail.com>", "tmfink <tmfinken@gmail.com>"]
description = "System bindings to the capstone disassembly library"
build = "build.rs"
links = "capstone"
license = "MIT"
readme = "README.md"
repository = "https://github.com/capstone-rust/capstone-sys"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.26.3"
pkg-config = "0.3"
gcc = "0.3"
cmake = {optional = true, version = "0.1.2"}
lazy_static = "0.2"

[features]
# use bundled capstone by default
default = []

use_system_capstone = []
build_capstone_cmake = ["cmake"]
use_bundled_capstone_bindings = []
